language: python
python:
  - '2.7'
  - '3.5'
  - 'pypy3.5'
branches:
  only:
  - release
before_install:
  - pip install -r requirements.txt
  - pip install z3-solver
  - pip install sqlite3
  - pip install SQLAlchemy
  - pip install PySide2
  - pip install Click
install:
  - python setup.py install
script:
  - python setup.py pytest
